### ISSUE TITLE
ArduCopter with Gazebo and SITL - problem with Circle mode

### ISSUE THREAD

**Issue by monabf** [AS4SR/general_info#2]
Hi all,

I have been simulating a drone in Gazebo 7.0 using Mavros with ArduCopter. Most modes work properly, but I have a problem with the Circle mode. From the [Ardupilot documentation](http://ardupilot.org/copter/docs/circle-mode.html), I understand that the nose of the drone should always be pointing towards the center of the circle, which is not the case for me. The drone is circling fine, I have no error messages anywhere, but its nose is always pointing forward instead of towards the center of the circle. I am not overwriting any yaw commands from the autopilot so it looks like this could be a bug in the Gazebo + mavros/SITL setup.  [Here](https://gist.github.com/monabf/39ada6784216edc2d39fbf67cc450260) is my small script if you want to take a look. 

If anyone has any ideas or has tried using Circle mode in Gazebo and can tell me how it went, that would be great! Any help is greatly appreciated!

**Comment by cmcghan** [comment]
Hi there! I'm not entirely sure, but I think that this may be a typo in the ArduPilot documentation. In any circling mode I've ever seen for fixed wing aircraft, one of the wings points towards the center of the circle, and the nose of the fixed-wing plane should be in the direction of motion (tangential to the circle). (Otherwise, I'd be worried about that plane! Think Dubins path vehicle, not ball-on-a-string.) It's possible/probable that they handled this the same way for the ArduCopter / helicopter implementation, and didn't actually set up the ArduCopter model to react that differently. I don't believe most helicopters circle while facing inwards at the center point of the circle; usually, they circle in a similar way as fixed-wing aircraft do (nose in the direction of motion), because of the flight dynamics involved.

In quickly searching around for an answer, I saw you also asked the mavlink/mavros and Gazebo developers? They and/or the Ardupilot folks are really the folks to ask this of; unfortunately, we are just end users like yourself. Sorry. I hope you were able to get an answer from the developers!
