### ISSUE TITLE
Not able to setup gazebo for ardupilot

### ISSUE THREAD

**Issue by padmashree9110** [AS4SR/general_info#3]
Hi,
 I followed below link for ardupilot and gazebo setup in Ubuntu 14.04,

https://github.com/AS4SR/general_info/wiki/ArduPilot:-Instructions-to-set-up-and-run-an-autopilot-using-SITL-and-Gazebo-simulator

But after running 

1> sim_vehicle.py -v ArduCopter -f gazebo-iris  -m --mav10 --map --console -I0
It is not getting connected to sitl 

Logs:
https://gist.github.com/padmashree9110/81323e79dbc3d80620490044ac3f0831

2> gazebo --verbose worlds/iris_irlock_demo.world
It is also giving error

Logs:
https://gist.github.com/padmashree9110/1f163c668cd6b0e14ad2952007cc1937

can anybody suggest me the solution.
Thank You

**Comment by cmcghan** [comment]
Under the SITL logs, you have:
"Unable to access the X Display, is $DISPLAY set properly?"

Under the gazebo logs, you have:
"[Err] [RenderEngine.cc:734] Can't open display: 
[Wrn] [RenderEngine.cc:97] Unable to create X window. Rendering will be disabled
[Wrn] [RenderEngine.cc:301] Cannot initialize render engine since render path type is NONE. Ignore this warning ifrendering has been turned off on purpose.
[Wrn] [GuiIface.cc:99] gazeb: cannot connect to X server"

This isn't a repository code problem.

You usually see this when you've used ssh to connect to a server, but didn't use a -X or -Y parameter to forward the XWindows displays to your local system. Alternately, you may see this if you have an Ubuntu server install, not a desktop install.

Either try:
$ ssh -Y ubuntu14@ubuntu14-B85M-D3H
...when you are logging in, if coming from another Linux instance or Mac OSX...

Or install and run XMing if connecting from Windows...
https://sourceforge.net/projects/xming/

Or install the XWin libraries under your Ubuntu O/S if you're running things locally; easiest way to get all the dependencies you need is to:
$ sudo apt-get update
$ sudo apt-get install gnome-terminal

Good luck! :)
