### ISSUE TITLE
md5 error

### ISSUE THREAD

**Issue by chrismath** [AS4SR/general_info#4]
When  i try to change the /mavros/state_mode service from STABLIZE to GUIDED it gives me a md5 error as shown below
unable to connect to service: remote error reported: client wants service /mavros/set_mode to have md5sum e4f18fa93379f9ff1780d270ce110203, but it has 48ecf639e39052f8856a839dcddf826a. Dropping connection.

**Comment by cmcghan** [comment]
This really isn't the place to put this, since mavros is something we use, not develop.

That said, I did a Google search, and found this:
https://answers.ros.org/question/245932/md5sum-issue-when-calling-a-service-from-another-computer/

Looks like you may just need to delete your workspace /devel and /build directories and rebuild everything?

Good luck!
