### ISSUE TITLE
excecuting planned path fails

### ISSUE THREAD

**Issue by C-monC** [AS4SR/general_info#5]
hello, gazebo and rviz opens and the robot exists in both after following the instructions. I am able to plan a path in rviz but when I click execute it fails. 

rviz console output:

`[ INFO] [1547041144.056322619, 82.876000000]: Execution request received
[ INFO] [1547041144.056411902, 82.876000000]: Returned 0 controllers in list
[ERROR] [1547041144.056466433, 82.876000000]: Unable to identify any set of controllers that can actuate the specified joints: [ joint_0 joint_1 joint_2 joint_3 joint_4 ]
[ERROR] [1547041144.056505510, 82.877000000]: Known controllers and their joints:

[ INFO] [1547041144.068116626, 82.888000000]: ABORTED: Solution found but controller failed during execution
`
Does someone have an idea of whats going wrong?

**Comment by cmcghan** [comment]
Looks like you're trying to control a manipulator arm, given the joint controllers. I'd need more information to give better help, but it looks like you don't have controllers attached / loaded in your model ("Unable to identify any set of controllers..."). If it's a model issue, then see:
https://answers.ros.org/question/192739/implement-moveit-on-real-robot/

If you're using something that's supposed to have a working model already, then you may not have all the ros controller libraries you need installed. (I've run into that a lot. It doesn't always toss an error properly when that happens.)

If you're using ROS kinetic, you might want to try running:
sudo apt get install ros-kinetic-ros-control ros-kinetic-ros-controllers ros-kinetic-gazebo-ros ros-kinetic-gazebo-ros-control ros-kinetic-control-toolbox
...and see if it installs anything new.

After that, close all terminal windows, then reopen a terminal window and try running whatever you're trying to run again, so that ROS will see the new packages in the environment.

Good luck!
